version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://root:root@db:5432/dbstc
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=dbstc

  test_db:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-test-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=testdb

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - ENV=test
      - DATABASE_URL=postgresql://root:root@test_db:5432/testdb
    depends_on:
      - test_db
    command: ["pytest", "--maxfail=1", "--disable-warnings", "-v"]
